GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/61f3f11d8e0a058e668b9770

###
GET http://localhost:3001/api/persons/61f3f11d8e0a158e668b9770